### ISSUE TITLE
Mailer: Notify admins on new Hackathon submission

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hackathons-backend#152]
Send an email to all admins whenever a new Hackathon is submitted

**Comment by carlospazuzu** [comment]
I would like to work on this issue!

**Comment by northeastprince** [comment]
Go for it!

**Comment by DanonymousCoder** [comment]
I would like to work on this

**Comment by garyhtou** [comment]
Hi @DanonymousCoder! Great to hear, although I believe @carlospazuzu has a work-in-progress PR open for this issue

https://github.com/hackclub/hackathons-backend/pull/186

There are handful of other issues open if you'd like to choose from them :)

**Comment by carlospazuzu** [comment]
It was already merged, so I think this issue may be closed.
