### ISSUE TITLE
Email sent after event aceptance

### ISSUE THREAD

**Issue by devramsean0** [hackclub/hackathons-backend#198]
When we used Airtable, our final step was to send an email to the submitte notifying that their event has been accepted (this was semi-automatic)
The new backend dossn't send this email.
I would appreciate if it sent this automatically on button press

**Comment by garyhtou** [comment]
Would you mind providing us with a template that you used when it was on Airtable? Do you generally include additional information as to why a hackathon was rejected?

**Comment by devramsean0** [comment]
We never had one for rejection.
But we did have one for airtable
```
Hey there,

Sean here from Hack Club Bank! Thanks for submitting your application to be featured on the Hack Club Hackathons page. This email is just to confirm that your submission has been added to the site. Congrats and best of luck with {name} ✨

https://hackathons.hackclub.com/

Best,
Sean and the Hack Club Bank Team
```

**Comment by garyhtou** [comment]
Thanks for that! So just to double check, we don't notify applicants when their hackathon is rejected

**Comment by garyhtou** [comment]
Also, would you like the ability to customize the email being sent? In other words, you're provided a template that you can edit before sending. If so, how important would that feature be?

**Comment by devramsean0** [comment]
We don't use that system for rejections. I don't think being able to edit the emails is important
