### ISSUE TITLE
Dashboard: List Users & Subscriptions

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hackathons-backend#36]
For admins only.

Implement the following:
- User index (list)
- User subscriptions index (list) as nested resources (e.g. `/users/:id/subscriptions`)

One of the goals of this is that Admins can manage user's subscriptions (mainly unsubscribing)

**Comment by garyhtou** [comment]
I'm pinning this issue to bring more visibility to it. I'd love to have this prioritized so operations can handle unsubscribe requests themselves. Currently, unsub requests are taking up some of my time

cc @northeastprince

**Comment by northeastprince** [comment]
Yeah, I saw you doing some of those via the console. Why couldn't they just click on the unsubscribe link?

**Comment by garyhtou** [comment]
Some users are marking emails as spam. As a result, AWS sends an email that looks like this. These emails are received by HCB Operations
![image](https://github.com/hackclub/hackathons-backend/assets/20099646/12847fb2-ba75-48d2-8eb0-4a63004d8508)

**Comment by northeastprince** [comment]
Are these legit users? If so, that seems odd, as the only way you get emails from us is if you subscribe.
