### ISSUE TITLE
Cant get notified for hackathons in the area

### ISSUE THREAD

**Issue by Ianyourgod** [hackclub/hackathons-backend#474]
No matter what location i put in, it doesnt find it. Even if i put in the example "Chicago, IL", it still says that the location is not found. 
I put this here instead of the frontend because i checked the network tab and its getting the error from the server.

**Comment by jaspermayone** [comment]
Hey! Thanks for giving us a heads up! We've be investigating this already, and will hopefully have a solution soon!
