### ISSUE TITLE
Fix testing setup

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hackathons-backend#87]
There appears to be something wrong with our tests.
- The wrong database is being used
- We also get errors like `Selenium::WebDriver::Error::UnknownError: unknown error: net::ERR_CONNECTION_REFUSED` on CI

---

I'd also love to move to rspec + factory_bot

**Comment by northeastprince** [comment]
This seems to be a problem with GitHub Actions, as the tests run locally. Regarding rspec, [this article](https://brandonhilkert.com/blog/7-reasons-why-im-sticking-with-minitest-and-fixtures-in-rails/) pretty much captures my thoughts on it and unless there's a huge benefit that outweighs the complexity it adds, I'd prefer to stick with the default testing stack, at least for now.

**Comment by northeastprince** [comment]
@garyhtou what did you mean by using the wrong database?

**Comment by northeastprince** [comment]
Closing as tests seem to be working.
